export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FALSE = 'AUTH_FALSE';
export const REG_SUCCESS = 'REG_SUCCESS';
export const REG_FALSE = 'REG_FALSE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
export const RENDER_ITEMS_SUCCESS = 'RENDER_ITEMS_SUCCESS';